FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1 \
	PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install -r requirements.txt --index-url https://pypi.tuna.tsinghua.edu.cn/simple

COPY api ./api
COPY sesora ./sesora
COPY run_pipeline ./run_pipeline
COPY data ./data

EXPOSE 8000

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]